# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'CocoaPodsAula' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for CocoaPodsAula
  pod 'lottie-ios'
  pod 'DragDropUI', :git => 'https://github.com/thejohnlima/DragDropUI.git', :branch => 'master'

end
